### ISSUE TITLE
Using toBeOnTheScreen() matcher requires @testing-library/react-native v10.1.0 or later to be added to your devDependencies

### ISSUE THREAD

**Issue by lvndry** [testing-library/jest-native#159]
- `expo`: 43.0.1
- `@testing-library/react-native` version: 12.0.0
- `jest-preset`:
- `react-native` version: 0.68.5
- `node` version: 16.17.1

### Relevant code or config:

```js
import * as React from "react";
import { render, screen } from "../../__test__/test-renderer";

import MyComponent from "./MyComponent";

describe("Test MyComponent", () => {
  it("should render correctly", () => {
    render(
      <MyComponent />,
    );

    const elementInComponent = screen.getByTestId("test-id");
    expect(elementInComponent).toBeOnTheScreen();
  });
});
```

### What you did:

pnpm test

### What happened:
Got the following error:

```
 Could not import `screen` object from @testing-library/react-native.

    Using toBeOnTheScreen() matcher requires @testing-library/react-native v10.1.0 or later to be added to your devDependencies.
```

### Problem description:

I'm on version 12.0.0 of @testing-library/react-native so this is an unexpected error.

### Suggested solution:

- Could it be related to pnpm dependency management ?

**Comment by mdjastrzebski** [comment]
@lvndry My suspicion is that you might have multiple versions of RNTL in your `yarn.lock`/`package-json.lock`.  Pls check that first.

If this is not the case, then pls prepare a minimal reproduction repository based on [RNTL basic example](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic), so that we could diagnose the error.

**Comment by mdjastrzebski** [comment]
Closing as stale.
