### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/jest-native#31]
Is anyone interested in helping maintain this project. The primary maintainer is no longer able to maintain it.

**Comment by brunohkbx** [comment]
I'd love to help maintain this lib :smiley:

**Comment by kentcdodds** [comment]
Thanks so much for your help! I've added you as a collaborator on the project. Maintaining this project is similar to React Testing Library, so please make sure that you review React Testing Library's [`other/MAINTAINING.md`](https://github.com/testing-library/react-testing-library/blob/master/other/MAINTAINING.md) and [`CONTRIBUTING.md`](https://github.com/testing-library/react-testing-library/blob/master/CONTRIBUTING.md) files (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

Also, if you feel like the PRs you've made are ready to go feel free to merge them, just make sure you use the "Squash and merge" feature so you can reword the commit message so the automation tools will release it with the proper version.

**Comment by thymikee** [comment]
Happy to help as well :)

**Comment by kentcdodds** [comment]
Awesome. Note that you don't *have* to use the existing automation tools as they are if you don't like. Feel free to change things up however you like.

**Comment by mitramejia** [comment]
@kentcdodds would love to help!

**Comment by mdjastrzebski** [comment]
@kentcdodds heads up that we are working on migrating Jest Native matchers to inside React Native Testing Library package: https://github.com/callstack/react-native-testing-library/issues/1468.

Since RNTL is the primary consumer of Jest Native matchers (except perhaps for hardcode users of React Test Renderer) it would benefit the users by:
* brining Jest Native matchers into well maintained project
* aligning JN with RNTL implementation in regard of RN env simulation (both RNTL & JN do not use actual React Native renderer but React Test Renderer and simulate the RN env)
* removing potential version discrepancy between RNTL and JN

This package would be kept as-is for legacy users. We would add deprecation notice and link to migration docs. Additionally, we will provide a gradual migration path where matches from this package can be imported in alternative way as `legacy_toXX`, so that users can use both JN and RNTL matchers at the same time.

**Comment by kentcdodds** [comment]
That's fine with me @mdjastrzebski 👍 As I'm not a user of the project I don't really have a place to have an opinion, but thanks for the heads up.

**Comment by mdjastrzebski** [comment]
Closing as resolved due to migration of matchers to React Native Testing Library.
