### ISSUE TITLE
Add a way to test Modal components

### ISSUE THREAD

**Issue by Goldziher** [testing-library/jest-native#49]
Hi,

Its very difficult to test the Modal component in RN directly at present. It would be awesome if: 

1. there is some way to directly select the modal element
2. check if the modal "visible" prop is in place, i.e. use a matcher like "toBeVisible()"

If not 1 & 2, it would be great if we could check if components within a modal are in fact visible or not.

**Comment by fluiddot** [comment]
👋 I'd like to share that I'm working on adding the `toBeVisible` matcher in [this PR](https://github.com/testing-library/jest-native/pull/73) following a similar logic as the same `jest-dom` matcher ([reference](https://github.com/testing-library/jest-dom#tobevisible)). I think this matcher would be useful for covering cases like the one described above by @Goldziher, in order to check the visibility of the `Modal` component.

**Comment by fluiddot** [comment]
> 👋 I'd like to share that I'm working on adding the `toBeVisible` matcher in [this PR](https://github.com/testing-library/jest-native/pull/73) following a similar logic as the same `jest-dom` matcher ([reference](https://github.com/testing-library/jest-dom#tobevisible)). I think this matcher would be useful for covering cases like the one described above by @Goldziher, in order to check the visibility of the `Modal` component.

After applying some updates, [the PR](https://github.com/testing-library/jest-native/pull/73) is now ready to be reviewed 🎊 .

**Comment by mdjastrzebski** [comment]
Resolved by #73
