### ISSUE TITLE
toHaveStyle support for styled-components

### ISSUE THREAD

**Issue by Pipo93** [testing-library/jest-native#6]
Since many projects are using styled-components for styling their react-native components, it would be nice if toHaveStyle would support it instead of just supporting the style property.

**Comment by bcarroll22** [comment]
Hello again 👋

My question is, does styled components not ultimately pass its styles into the native components? I’m fairly certain this matcher does support styled components because its styles have to end up being passed into the native components. I assume what you’re trying to do is select the styled wrapper and not the native node itself, which wouldn’t work. You can only select the native node and assert that the proper styles were given to it. 

If that’s not true and somehow styled components doesn’t pass styles to native nodes, could you please provide `debug()` output of a small styled component example?

**Comment by bcarroll22** [comment]
I'm gonna go ahead and close this due to inactivity. I'm not sure this is something that should be supported from within this library because support for it would be so specific to styled-components, but I'd encourage you to explore building a third-party matcher that would fulfill your needs and then submit a PR to the docs to add it to the ecosystem. 

Good luck and I look forward to hopefully seeing your matcher implementation! 😄

**Comment by mikinw** [comment]
I have the same (similar) issue. There is a component:
`<MaterialIcons
            testID="iconID"
            style={[styles.icon, {backgroundColor: '#ff0000'}]}
          />`

the styles.js looks like this:
`  icon: {
    color: Colors.paleWhite,
  },`

When I create a snapshot, it gives me this:
`...
<Text
        allowFontScaling={false}
        style={
          Array [
            Object {
              "color": undefined,
              "fontSize": 22,
            },
            Array [
              Object {
                "color": "#EDEDED",
                "margin": 15,
              },
              Object {
                "backgroundColor": "#7692DD",
              },
            ],
            Object {
              "fontFamily": "Material Icons",
              "fontStyle": "normal",
              "fontWeight": "normal",
            },
            Object {},
          ]
        }
        testID="iconID"
      >`

But when I try to match against a style `expect(sut.queryByTestId('iconID')).toHaveStyle([
    {fontFamily: 'Material Icons', backgroundColor: '#ff0000'},
  ]);`

It can't find backgroundColor. It does find fontFamily.
